parameters:
#    malwarebytes_altamira.example.class: Malwarebytes\AltamiraBundle\Example

services:
#    malwarebytes_altamira.example:
#        class: %malwarebytes_altamira.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]


services:
    charts_factory:
        class: Malwarebytes\AltamiraBundle\ChartFactory
        arguments: [ %malwarebytes_altamira.library_type% , @logger]
        tags:
            - { name: monolog.logger, channel: malwarebytes } 
